# This is a basic workflow to help you get started with Actions

name: Build and push to ACR and AKS


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ACRNAME: acrdevdemo.azurecr.io

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  acr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USERNAME }}
          # Container registry password
          password: ${{ secrets.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${ACRNAME}
      - run: |
          docker build ./api -t ${ACRNAME}/aksdemo/api:${{ github.sha }}
          docker push ${ACRNAME}/aksdemo/api:${{ github.sha }}
  aks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: acr
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: step-2
        run: echo "Starting AKS deploy"
      
